server:
  port: 8082

spring:
  application:
    name: gestionare-studenti
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestionare
    username: postgres
    password: andrei

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

