server:
  port: 8082

spring:
  application:
    name: gestionare-studenti
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestionare
    username: postgres
    password: andrei

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

keycloak:
  realm: universitate
  auth-server-url: http://localhost:9000/auth
  ssl-required: external
  resource: andrei-demo
  bearer-only: true
  credentials:
    secret: a1735132-a862-4282-814f-1728ade599fe
  use-resource-role-mappings: true
  principal-attribute: preffered_username
  security-constraints:
    - authRoles:
        - ROLE_ADMIN
      securityCollections:
        - patterns:
            - /nomenclatoare/**
    - authRoles:
        - ROLE_PROFESOR
      securityCollections:
        - patterns:
            - /nomenclatoare/save-linii
    - authRoles:
        - ROLE_STUDENT
      securityCollections:
        - patterns:
            - /nomenclatoare/save-linii

