server:
  port: 8081

spring:
  application:
    name: zuul-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    gestionare-studenti:
      path: /gestionare-studenti/**
      serviceId: gestionare-studenti
      stripPrefix: true
  prefix: /api

ribbon:
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
